export type DietType = "all" | "vegetarian" | "vegan";

export interface DishOption {
  id: string;
  name: string;
  category: "breakfast" | "lunch" | "shake" | "dinner";
  dietType: "vegetarian" | "vegan" | "balanced";
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  description: string;
  ingredients: string[];
  prepTime: string;
  highlight: string;
}

export interface MealSlot {
  id: "breakfast" | "lunch" | "shake" | "dinner";
  title: string;
  time: string;
  subtitle: string;
}

export const MEAL_SLOTS: MealSlot[] = [
  { id: "breakfast", title: "Morning Fuel (Nashta)", time: "07:30 – 09:00", subtitle: "High protein & complex carbs to awaken metabolism & energy" },
  { id: "lunch", title: "Midday Mass Anchor (Dopahar Ka Khana)", time: "13:00 – 14:30", subtitle: "Heavy Indian staples: Dal, Paneer/Chicken/Soya, Roti & Rice" },
  { id: "shake", title: "Anabolic Shake / Desi Snack", time: "17:00 – 18:00", subtitle: "Sattu, whey, makhana or dry-fruit shakes for easy calories" },
  { id: "dinner", title: "Night Recovery Feast (Raat Ka Khana)", time: "20:30 – 21:30", subtitle: "Slow-digesting protein & restorative carbs for deep sleep" },
];

export const DISH_DATABASE: DishOption[] = [
  // =========================================================================
  // BREAKFAST (NASHTA)
  // =========================================================================

  // --- VEGETARIAN (DESI SHAKAHARI) ---
  {
    id: "ind-veg-b-1",
    name: "Desi Paneer Bhurji with 3 Multigrain Rotis & Curd",
    category: "breakfast",
    dietType: "vegetarian",
    calories: 840,
    protein: 48,
    carbs: 82,
    fats: 36,
    description: "200g crumbled fresh paneer sautéed with onions, green chillies, tomatoes, and turmeric, served with 3 multigrain rotis with ghee and 1 cup fresh dahi.",
    ingredients: ["200g Fresh Malai/Low-fat Paneer", "3 Multigrain Rotis with Ghee", "1 cup Fresh Dahi (Curd)", "Onion, Tomato & Green Chilli", "Jeera & Turmeric"],
    prepTime: "15 min",
    highlight: "48g of slow-digesting casein protein and calcium to sustain muscles throughout morning training.",
  },
  {
    id: "ind-veg-b-2",
    name: "Sprouted Moong Dal Chilla with Grated Paneer & Mint Chutney",
    category: "breakfast",
    dietType: "vegetarian",
    calories: 780,
    protein: 44,
    carbs: 86,
    fats: 28,
    description: "3 thick sprouted green moong dal savoury pancakes stuffed with grated paneer, fresh coriander, and spices, served with fresh mint peanut chutney.",
    ingredients: ["1.5 cups Sprouted Moong Dal Batter", "150g Grated Paneer", "2 tbsp Peanut Mint Chutney", "Ginger & Green Chillies", "1 tsp Desi Ghee"],
    prepTime: "15 min",
    highlight: "Sprouted moong has higher bioavailability and enzymatic activity with zero bloating.",
  },
  {
    id: "ind-veg-b-3",
    name: "2 Stuffed Paneer Parathas with White Butter & Mithi Dahi",
    category: "breakfast",
    dietType: "vegetarian",
    calories: 870,
    protein: 42,
    carbs: 96,
    fats: 38,
    description: "2 large golden parathas generously stuffed with seasoned paneer and fresh herbs, served with 1 dollop of homemade white butter and 1 bowl of curd.",
    ingredients: ["200g Paneer Filling", "2 Whole-Wheat Parathas", "1 tbsp White Butter (Makhan)", "1 bowl Fresh Curd", "Ajwain & Spices"],
    prepTime: "20 min",
    highlight: "Traditional North Indian mass-builder classic delivering sustained energy for hours.",
  },
  {
    id: "ind-veg-b-4",
    name: "Kala Chana & Sprouted Moong Chaat with Sweet Sattu Lassi",
    category: "breakfast",
    dietType: "vegetarian",
    calories: 760,
    protein: 42,
    carbs: 104,
    fats: 20,
    description: "Boiled desi black chickpeas, sprouted green moong, roasted peanuts, diced onions, tomatoes, and lemon chaat, paired with a glass of sweetened sattu curd lassi.",
    ingredients: ["1 cup Boiled Kala Chana", "1 cup Sprouted Moong", "30g Roasted Peanuts", "40g Roasted Chana Sattu", "1 cup Curd Lassi"],
    prepTime: "10 min",
    highlight: "High in prebiotic dietary fiber, iron, and plant protein for steady energy.",
  },

  // --- VEGAN (SHUDDH VEGAN) ---
  {
    id: "ind-vgn-b-1",
    name: "Tofu Matar Bhurji with 3 Multigrain Rotis & Mint Chutney",
    category: "breakfast",
    dietType: "vegan",
    calories: 780,
    protein: 42,
    carbs: 88,
    fats: 28,
    description: "250g organic firm tofu crumbled and cooked bhurji-style with tender green peas, ginger, garlic, tomatoes, and aromatic turmeric, paired with 3 multigrain rotis.",
    ingredients: ["250g Firm Tofu", "1/2 cup Green Peas", "3 Multigrain Rotis (Ghee-Free)", "Tomato, Onion & Ginger", "Spicy Coriander Mint Chutney"],
    prepTime: "15 min",
    highlight: "100% plant-based complete protein with zero cholesterol and optimal digestibility.",
  },
  {
    id: "ind-vgn-b-2",
    name: "High-Protein Besan & Sprouted Moong Chilla with Peanut Chutney",
    category: "breakfast",
    dietType: "vegan",
    calories: 750,
    protein: 38,
    carbs: 92,
    fats: 24,
    description: "3 large savoury gram flour and sprouted green gram crepes stuffed with finely chopped onions, chillies, and crushed peanuts, served with coconut-peanut dip.",
    ingredients: ["1 cup Besan (Gram Flour)", "1 cup Ground Moong Dal", "30g Crushed Roasted Peanuts", "Ajwain & Hing", "Green Chillies & Coriander"],
    prepTime: "15 min",
    highlight: "Gram flour (Besan) has high resistance starch and clean plant protein.",
  },
  {
    id: "ind-vgn-b-3",
    name: "Banarasi Sattu Drink with Boiled Kala Chana Chaat",
    category: "breakfast",
    dietType: "vegan",
    calories: 720,
    protein: 40,
    carbs: 98,
    fats: 18,
    description: "2 large glasses of authentic savory roasted chana sattu with roasted jeera, rock salt, mint, and lemon juice, served with a big bowl of boiled black chickpea chaat.",
    ingredients: ["70g Roasted Chana Sattu", "1.5 cups Boiled Kala Chana", "Roasted Cumin & Black Salt", "Lemon & Mint", "20g Roasted Peanuts"],
    prepTime: "5 min",
    highlight: "India's indigenous superfood: pure roasted Bengal gram loaded with iron and plant protein.",
  },

  // --- BALANCED / NON-VEG (DESI MANSAHARI) ---
  {
    id: "ind-bal-b-1",
    name: "4-Egg Desi Bhurji with 2 Stuffed Parathas & Dahi",
    category: "breakfast",
    dietType: "balanced",
    calories: 880,
    protein: 48,
    carbs: 76,
    fats: 42,
    description: "4 whole farm eggs scrambled with desi ghee, green chillies, diced onions, tomatoes, and coriander, served with 2 wheat parathas and 1 cup fresh dahi.",
    ingredients: ["4 Whole Eggs", "2 Whole-Wheat Parathas", "1 cup Fresh Dahi", "1 tbsp Desi Ghee", "Onion, Tomato & Green Chilli"],
    prepTime: "15 min",
    highlight: "High biological value egg protein containing all essential amino acids for fast absorption.",
  },
  {
    id: "ind-bal-b-2",
    name: "Desi Chicken Keema Ghotala with 3 Whole-Wheat Pav / Roti",
    category: "breakfast",
    dietType: "balanced",
    calories: 860,
    protein: 56,
    carbs: 68,
    fats: 38,
    description: "220g spiced minced chicken breast cooked with cumin, garam masala, and 1 folded-in sunny egg, served with 3 toasted whole-wheat pavs or rotis.",
    ingredients: ["220g Minced Chicken Breast", "1 Whole Egg", "3 Whole-Wheat Pav / Rotis", "1 tbsp Ghee", "Ginger Garlic Paste"],
    prepTime: "20 min",
    highlight: "56g of lean protein in a savory Parsi/Mumbai style high-energy breakfast.",
  },
  {
    id: "ind-bal-b-3",
    name: "4 Boiled Eggs, Peanut Butter Roti & Banana Shake",
    category: "breakfast",
    dietType: "balanced",
    calories: 810,
    protein: 48,
    carbs: 88,
    fats: 30,
    description: "4 boiled eggs sprinkled with black salt and chaat masala, 2 warm rotis spread with natural peanut butter, and 1 glass of banana milk shake.",
    ingredients: ["4 Hard-Boiled Eggs", "2 Whole-Wheat Rotis", "2 tbsp Peanut Butter", "1 Banana", "250ml Milk"],
    prepTime: "10 min",
    highlight: "Fast, minimal cooking breakfast balancing fast-acting carbs and solid protein.",
  },

  // =========================================================================
  // LUNCH (DOPAHAR KA KHANA)
  // =========================================================================

  // --- VEGETARIAN (DESI SHAKAHARI) ---
  {
    id: "ind-veg-l-1",
    name: "Soya Chunks & Green Peas Matar Pulao with Tadka Dahi",
    category: "lunch",
    dietType: "vegetarian",
    calories: 940,
    protein: 56,
    carbs: 115,
    fats: 26,
    description: "90g Nutrela soya chunks (over 47g protein alone!) cooked with fragrant basmati rice, green peas, roasted cashews, served with roasted cumin tadka dahi.",
    ingredients: ["90g Nutrela Soya Chunks", "2 cups Cooked Basmati Rice", "1/2 cup Green Peas", "250g Fresh Curd with Jeera Tadka", "20g Cashews"],
    prepTime: "25 min",
    highlight: "Soya chunks contain over 52% pure protein by dry weight, beating even poultry density.",
  },
  {
    id: "ind-veg-l-2",
    name: "Punjabi Rajma Masala with Basmati Rice & Paneer Cubes",
    category: "lunch",
    dietType: "vegetarian",
    calories: 920,
    protein: 48,
    carbs: 120,
    fats: 28,
    description: "Authentic slow-cooked Jammu rajma in rich ginger-tomato gravy, 2 cups steamed basmati rice, 150g grilled paneer cubes, and sliced pickled onions.",
    ingredients: ["1.5 cups Boiled Red Rajma", "2 cups Steamed Basmati Rice", "150g Fresh Paneer Cubes", "1 tbsp Ghee", "Kashmiri Spices & Ginger"],
    prepTime: "30 min",
    highlight: "Complete amino acid profile formed by the timeless pairing of beans and rice.",
  },
  {
    id: "ind-veg-l-3",
    name: "Chole Paneer with 3 Ghee Rotis, Jeera Rice & Chaas",
    category: "lunch",
    dietType: "vegetarian",
    calories: 910,
    protein: 46,
    carbs: 118,
    fats: 30,
    description: "Spicy Amritsari white chickpeas with paneer cubes simmered in roasted anardana gravy, served with 3 soft wheat rotis, cumin rice, and spiced buttermilk.",
    ingredients: ["1.5 cups Boiled Kabuli Chana", "120g Paneer", "3 Whole-Wheat Rotis", "1 cup Jeera Rice", "1 glass Masala Chaas"],
    prepTime: "25 min",
    highlight: "Rich in zinc, complex carbohydrates, and gut-friendly fermented buttermilk probiotics.",
  },
  {
    id: "ind-veg-l-4",
    name: "Thick Toor Dal Tadka, Paneer Bhurji & 4 Ghee Phulkas",
    category: "lunch",
    dietType: "vegetarian",
    calories: 880,
    protein: 50,
    carbs: 102,
    fats: 32,
    description: "Traditional protein-dense yellow dal with garlic-ghee tadka, 180g dry spicy paneer bhurji, 4 soft phulkas with pure cow ghee, and raw cucumber-carrot salad.",
    ingredients: ["1.5 cups Boiled Toor/Arhar Dal", "180g Paneer Bhurji", "4 Phulkas with A2 Ghee", "Garlic & Hing Tadka", "Salad"],
    prepTime: "20 min",
    highlight: "Simple, highly digestible home staple packed with 50g of clean vegetarian protein.",
  },

  // --- VEGAN (SHUDDH VEGAN) ---
  {
    id: "ind-vgn-l-1",
    name: "Nutrela Soya Chunks & Aloo Curry with 2 Cups Basmati Rice",
    category: "lunch",
    dietType: "vegan",
    calories: 910,
    protein: 58,
    carbs: 118,
    fats: 22,
    description: "100g juicy soya chunks simmered in thick Punjabi tomato onion gravy with baby potatoes, served with 2 cups steamed basmati rice and roasted peanuts.",
    ingredients: ["100g Soya Chunks", "2 cups Basmati Rice", "1 medium Potato", "Tomato Onion Gravy", "30g Roasted Peanuts"],
    prepTime: "25 min",
    highlight: "Massive 58g of pure plant protein and zero saturated animal fat.",
  },
  {
    id: "ind-vgn-l-2",
    name: "Spicy Tandoori Soya Chaap with 3 Multigrain Rotis & Chana",
    category: "lunch",
    dietType: "vegan",
    calories: 890,
    protein: 52,
    carbs: 108,
    fats: 26,
    description: "220g soya chaap sticks marinated in mustard oil, roasted gram flour, and spices, roasted golden and served with boiled black chana and 3 multigrain rotis.",
    ingredients: ["220g Soya Chaap (Soy/Wheat)", "3 Multigrain Rotis", "1 cup Boiled Kala Chana", "Mustard Oil Marinade", "Mint Onion Salad"],
    prepTime: "25 min",
    highlight: "High elasticity plant protein that mimics meat texture with superior leucine content.",
  },
  {
    id: "ind-vgn-l-3",
    name: "Desi Rajma Chawal with Roasted Peanut Kachumber Salad",
    category: "lunch",
    dietType: "vegan",
    calories: 860,
    protein: 42,
    carbs: 122,
    fats: 20,
    description: "Kashmiri red kidney beans cooked in aromatic spices with zero dairy, served over 2.5 cups steamed basmati rice with a crunchy peanut-cucumber kachumber.",
    ingredients: ["2 cups Boiled Rajma", "2.5 cups Steamed Rice", "40g Roasted Peanuts", "Cucumber, Tomato & Coriander", "Mustard Oil"],
    prepTime: "25 min",
    highlight: "Loaded with potassium and slow-burning complex carbs for sustained muscle glycogen.",
  },

  // --- BALANCED / NON-VEG (DESI MANSAHARI) ---
  {
    id: "ind-bal-l-1",
    name: "Dhabha Style Chicken Curry with 3 Ghee Rotis & Jeera Rice",
    category: "lunch",
    dietType: "balanced",
    calories: 960,
    protein: 65,
    carbs: 98,
    fats: 32,
    description: "280g tender chicken breast and thigh cooked in rustic dhabha onion-garlic-tomato gravy, served with 3 rotis brushed with desi ghee and 1 cup jeera rice.",
    ingredients: ["280g Chicken Breast & Thigh", "3 Whole-Wheat Rotis with Ghee", "1 cup Jeera Rice", "1 tbsp Desi Ghee", "Dhabha Onion Gravy"],
    prepTime: "30 min",
    highlight: "Unrivalled 65g of pure complete animal protein packed with natural creatine.",
  },
  {
    id: "ind-bal-l-2",
    name: "Hyderabadi Chicken Dum Biryani with Boiled Egg & Dahi Raita",
    category: "lunch",
    dietType: "balanced",
    calories: 980,
    protein: 62,
    carbs: 110,
    fats: 34,
    description: "Fragrant saffron basmati rice layered with 250g spiced marinated chicken, 1 whole boiled egg, served with cool mint-onion curd raita.",
    ingredients: ["250g Marinated Chicken", "1 Whole Boiled Egg", "2 cups Dum Biryani Rice", "1 cup Onion Mint Raita", "Saffron & Whole Spices"],
    prepTime: "35 min",
    highlight: "The crown jewel of Indian fitness cuisine: heavy mass-building calories and protein.",
  },
  {
    id: "ind-bal-l-3",
    name: "Kerala / Bengali Fish Curry with Steamed Rice & Greens",
    category: "lunch",
    dietType: "balanced",
    calories: 880,
    protein: 54,
    carbs: 96,
    fats: 28,
    description: "250g fresh Surmai, Rohu or Kingfish steak simmered in aromatic coconut or mustard-fenugreek curry, served with 2 cups steamed rice and vegetable stir-fry.",
    ingredients: ["250g Fresh Fish Fillet", "2 cups Steamed Basmati Rice", "Mustard / Coconut Kokum Gravy", "1 cup Sautéed Spinach", "Green Chillies"],
    prepTime: "25 min",
    highlight: "Abundant bioavailable marine Omega-3s that accelerate post-workout recovery.",
  },
  {
    id: "ind-bal-l-4",
    name: "Mutton Keema Matar with 3 Whole-Wheat Rotis & Salad",
    category: "lunch",
    dietType: "balanced",
    calories: 940,
    protein: 58,
    carbs: 82,
    fats: 42,
    description: "220g lean minced mutton/goat meat slow-cooked with green peas, cumin, black cardamom, and ginger, paired with 3 warm rotis and lemon wedges.",
    ingredients: ["220g Lean Mutton Keema", "1/2 cup Green Peas", "3 Whole-Wheat Rotis with Ghee", "Ginger Garlic & Garam Masala", "Onion Salad"],
    prepTime: "35 min",
    highlight: "Loaded with bioavailable heme iron, carnitine, and zinc to optimize testosterone production.",
  },

  // =========================================================================
  // ANABOLIC SHAKE / DESI SNACK (SHAAM KA NASHTA)
  // =========================================================================

  // --- VEGETARIAN (DESI SHAKAHARI) ---
  {
    id: "ind-veg-s-1",
    name: "Desi Sattu & Peanut Butter Mass Gainer Shake",
    category: "shake",
    dietType: "vegetarian",
    calories: 790,
    protein: 52,
    carbs: 86,
    fats: 28,
    description: "60g roasted Chana Sattu, 400ml creamy buffalo/cow milk, 1 scoop whey or 2 tbsp natural peanut butter, 1 large banana, and desi jaggery (gur) blended thick.",
    ingredients: ["60g Roasted Chana Sattu", "400ml Milk", "2 tbsp Natural Peanut Butter", "1 scoop Whey Isolate (or extra Sattu)", "1 Banana & Jaggery"],
    prepTime: "3 min",
    highlight: "India's indigenous gainer shake: delivers 52g protein and over 750 kcal in 60 seconds.",
  },
  {
    id: "ind-veg-s-2",
    name: "Air-Fried Paneer Tikka Cubes & Roasted Makhana Box",
    category: "shake",
    dietType: "vegetarian",
    calories: 690,
    protein: 46,
    carbs: 52,
    fats: 32,
    description: "200g paneer cubes marinated in hung curd and tandoori spices, air-fried crisp, served with 2 cups roasted crunchy lotus seeds (makhana) with black salt.",
    ingredients: ["200g Fresh Paneer", "2 cups Roasted Makhana (Fox Nuts)", "2 tbsp Hung Curd", "Tandoori Spices & Lemon", "1 tsp Ghee"],
    prepTime: "10 min",
    highlight: "Crunchy, low-sodium savory snack packed with calcium and slow-burning protein.",
  },
  {
    id: "ind-veg-s-3",
    name: "Dry Fruit & Makhana Whey Rabri Shake",
    category: "shake",
    dietType: "vegetarian",
    calories: 740,
    protein: 48,
    carbs: 78,
    fats: 26,
    description: "Whole milk blended with crushed soaked almonds, cashews, roasted makhana powder, 1 scoop vanilla whey, cardamom, and saffron strands.",
    ingredients: ["400ml Whole Milk", "1 scoop Vanilla Whey", "20g Soaked Almonds", "15g Cashews", "1/2 cup Makhana Powder", "Kesar & Elaichi"],
    prepTime: "4 min",
    highlight: "Decadent traditional taste engineered with modern muscle-building macronutrients.",
  },

  // --- VEGAN (SHUDDH VEGAN) ---
  {
    id: "ind-vgn-s-1",
    name: "Desi Sattu & Soy Milk Power Gainer Shake",
    category: "shake",
    dietType: "vegan",
    calories: 760,
    protein: 48,
    carbs: 88,
    fats: 24,
    description: "70g roasted Chana Sattu, 450ml organic unsweetened soy milk, 2.5 tbsp natural peanut butter, 1 Robusta banana, and a pinch of cinnamon.",
    ingredients: ["70g Roasted Chana Sattu", "450ml Soy Milk", "2.5 tbsp Peanut Butter", "1 Banana", "Jaggery or Dates for sweetness"],
    prepTime: "3 min",
    highlight: "Dual plant-protein powerhouse combining the amino acid profiles of Bengal gram and soybeans.",
  },
  {
    id: "ind-vgn-s-2",
    name: "Roasted Makhana, Peanut & Sprouted Moong Bhel",
    category: "shake",
    dietType: "vegan",
    calories: 620,
    protein: 34,
    carbs: 72,
    fats: 22,
    description: "Crunchy roasted fox nuts (makhana), roasted peanuts, steamed sprouted green moong, diced onion, tomato, lemon juice, and roasted cumin powder.",
    ingredients: ["2 cups Roasted Makhana", "40g Roasted Salted Peanuts", "1 cup Sprouted Moong", "Lemon, Chaat Masala & Coriander", "Tomatoes & Onion"],
    prepTime: "5 min",
    highlight: "Light on the gut yet delivering 34g of natural plant protein with zero dairy.",
  },

  // --- BALANCED / NON-VEG (DESI MANSAHARI) ---
  {
    id: "ind-bal-s-1",
    name: "Desi Titan Milk & Whey Mass Gainer Shake",
    category: "shake",
    dietType: "balanced",
    calories: 820,
    protein: 58,
    carbs: 84,
    fats: 28,
    description: "450ml full-cream milk, 2 scoops chocolate whey protein, 2 tbsp natural peanut butter, 1 banana, and 1/2 cup blended oats with honey.",
    ingredients: ["450ml Full-Cream Milk", "2 scoops Whey Isolate", "2 tbsp Peanut Butter", "1 large Banana", "1/2 cup Oats", "1 tbsp Honey"],
    prepTime: "3 min",
    highlight: "58g of rapid-acting whey and casein protein to spark immediate post-workout recovery.",
  },
  {
    id: "ind-bal-s-2",
    name: "Tandoori Chicken Tikka Skewers (220g) with Mint Chutney",
    category: "shake",
    dietType: "balanced",
    calories: 520,
    protein: 54,
    carbs: 12,
    fats: 24,
    description: "220g juicy boneless chicken breast chunks marinated in hung curd, garlic, ginger, and Kashmiri spices, grilled in tandoor or air-fryer, served with onion rings.",
    ingredients: ["220g Chicken Breast", "2 tbsp Hung Curd", "Ginger Garlic Paste", "Kashmiri Lal Mirch & Garam Masala", "Mint Coriander Chutney"],
    prepTime: "15 min",
    highlight: "Pure protein snack: 54g protein with almost zero carbs for clean hypertrophy.",
  },
  {
    id: "ind-bal-s-3",
    name: "4 Boiled Egg Whites & 2 Whole Eggs with Masala Chai",
    category: "shake",
    dietType: "balanced",
    calories: 540,
    protein: 42,
    carbs: 34,
    fats: 22,
    description: "4 boiled egg whites + 2 whole boiled eggs tossed in black pepper and chaat masala, paired with 2 slices of multigrain peanut toast and ginger masala tea.",
    ingredients: ["6 Eggs (4 whites, 2 whole)", "2 slices Multigrain Bread", "1 tbsp Peanut Butter", "Chaat Masala", "Ginger Chai"],
    prepTime: "10 min",
    highlight: "Classic gym-goer snack providing optimal albumin protein with zero crash.",
  },

  // =========================================================================
  // DINNER (RAAT KA KHANA)
  // =========================================================================

  // --- VEGETARIAN (DESI SHAKAHARI) ---
  {
    id: "ind-veg-d-1",
    name: "Shahi Dal Makhani & 150g Paneer with 3 Ghee Rotis",
    category: "dinner",
    dietType: "vegetarian",
    calories: 890,
    protein: 48,
    carbs: 104,
    fats: 34,
    description: "Slow-simmered black urad dal and rajma cooked with butter, paired with 150g tandoori or pan-seared paneer cubes, 3 whole-wheat rotis with ghee, and cucumber salad.",
    ingredients: ["1.5 cups Black Lentil Dal Makhani", "150g Fresh Paneer", "3 Whole-Wheat Rotis with Ghee", "1 tbsp Butter", "Sliced Onion & Lemon"],
    prepTime: "30 min",
    highlight: "Black lentils and paneer provide a steady 8-hour amino acid stream during overnight sleep.",
  },
  {
    id: "ind-veg-d-2",
    name: "Garlic Palak Paneer with 2 Cups Jeera Rice & Yellow Dal",
    category: "dinner",
    dietType: "vegetarian",
    calories: 860,
    protein: 46,
    carbs: 102,
    fats: 32,
    description: "Rich spinach purée cooked with garlic, cumin, and garam masala, loaded with 200g paneer cubes, served with 2 cups jeera rice and a bowl of yellow moong dal.",
    ingredients: ["200g Paneer Cubes", "2 bunches Spinach (Palak)", "2 cups Jeera Basmati Rice", "1 cup Moong Dal", "Garlic & Desi Ghee"],
    prepTime: "25 min",
    highlight: "Exceptional source of magnesium, iron, and slow-acting casein for overnight muscle recovery.",
  },
  {
    id: "ind-veg-d-3",
    name: "High-Protein Moong Dal & Paneer Khichdi with Desi Cow Ghee",
    category: "dinner",
    dietType: "vegetarian",
    calories: 820,
    protein: 44,
    carbs: 108,
    fats: 24,
    description: "Comforting Ayurvedic muscle khichdi made with split yellow moong dal, brown rice, 150g diced paneer, roasted cumin, and 2 tbsp pure A2 desi cow ghee.",
    ingredients: ["1 cup Split Moong Dal", "1 cup Brown Rice", "150g Paneer Cubes", "2 tbsp Pure Desi Cow Ghee", "Cumin, Hing & Ginger"],
    prepTime: "25 min",
    highlight: "Maximum digestive ease: zero stomach heaviness, ensuring deep, uninterrupted REM sleep.",
  },

  // --- VEGAN (SHUDDH VEGAN) ---
  {
    id: "ind-vgn-d-1",
    name: "High-Protein Soya Bhurji & 3 Multigrain Rotis with Tadka Dal",
    category: "dinner",
    dietType: "vegan",
    calories: 880,
    protein: 56,
    carbs: 104,
    fats: 22,
    description: "90g dehydrated soya granules rehydrated and stir-fried bhurji-style with onions, green peas, and tomatoes, served with toor dal and 3 multigrain rotis.",
    ingredients: ["90g Soya Granules", "1/2 cup Green Peas", "1.5 cups Toor Dal", "3 Multigrain Rotis", "Onion, Tomato & Cumin"],
    prepTime: "20 min",
    highlight: "Unmatched 56g of plant protein ensuring maximum nitrogen balance through the night.",
  },
  {
    id: "ind-vgn-d-2",
    name: "Tandoori Tofu Tikka Masala with Jeera Rice & Chana Dal",
    category: "dinner",
    dietType: "vegan",
    calories: 840,
    protein: 46,
    carbs: 108,
    fats: 24,
    description: "220g spiced marinated tofu cubes simmered in creamy cashew-tomato curry, served with 2 cups jeera rice and a bowl of yellow chana dal.",
    ingredients: ["220g Firm Tofu", "2 cups Jeera Basmati Rice", "1 cup Chana Dal", "Cashew Tomato Gravy", "Kasuri Methi"],
    prepTime: "25 min",
    highlight: "Cashew cream provides healthy monounsaturated fats for hormone regulation.",
  },
  {
    id: "ind-vgn-d-3",
    name: "Traditional Kala Chana Masala with 3 Rotis & Roasted Peanuts",
    category: "dinner",
    dietType: "vegan",
    calories: 820,
    protein: 42,
    carbs: 115,
    fats: 20,
    description: "Hearty black desi chickpea curry simmered in dark roasted coriander and amchur gravy, served with 3 soft rotis and roasted spiced peanuts.",
    ingredients: ["1.5 cups Boiled Kala Chana", "3 Whole-Wheat Rotis", "35g Roasted Peanuts", "Amchur & Roasted Spices", "Kachumber Salad"],
    prepTime: "25 min",
    highlight: "Low glycemic index complex carbohydrates keep blood sugar steady overnight.",
  },

  // --- BALANCED / NON-VEG (DESI MANSAHARI) ---
  {
    id: "ind-bal-d-1",
    name: "Tandoori Murgh (Half Chicken) with Yellow Dal & 2 Ghee Rotis",
    category: "dinner",
    dietType: "balanced",
    calories: 920,
    protein: 66,
    carbs: 74,
    fats: 36,
    description: "300g bone-in chicken breast and leg marinated in curd and tandoori masala, charred in tandoor, paired with 1 bowl moong dal tadka, 2 ghee rotis, and salad.",
    ingredients: ["300g Chicken (Tandoori Half)", "1 cup Moong Dal", "2 Whole-Wheat Rotis with Ghee", "Tandoori Masala & Lemon", "Mint Onion Salad"],
    prepTime: "25 min",
    highlight: "66g of complete animal protein with high leucine to trigger nighttime muscle synthesis.",
  },
  {
    id: "ind-bal-d-2",
    name: "Boneless Butter Chicken (Athletic Clean Prep) with Jeera Rice",
    category: "dinner",
    dietType: "balanced",
    calories: 910,
    protein: 60,
    carbs: 94,
    fats: 32,
    description: "250g grilled chicken breast chunks simmered in a light cashew-tomato makhani gravy with minimal butter, served over 2 cups fragrant jeera basmati rice.",
    ingredients: ["250g Chicken Breast Chunks", "2 cups Jeera Basmati Rice", "Cashew Tomato Makhani Gravy", "1 tbsp Ghee/Butter", "Kasuri Methi"],
    prepTime: "25 min",
    highlight: "Authentic royal taste with clean bodybuilder macros: 60g protein and zero excess grease.",
  },
  {
    id: "ind-bal-d-3",
    name: "Bengali Machher Jhol (Mustard Fish Curry) with Steamed Rice",
    category: "dinner",
    dietType: "balanced",
    calories: 840,
    protein: 52,
    carbs: 96,
    fats: 26,
    description: "250g Rohu / Katla / Bhetki fish steaks cooked in light turmeric, kalonji, and mustard seed broth with potato wedges, served with 2 cups steamed rice.",
    ingredients: ["250g Fresh Fish Steaks", "2 cups Steamed Basmati Rice", "Mustard & Turmeric Broth", "1 Potato", "Green Chillies & Coriander"],
    prepTime: "20 min",
    highlight: "Light on digestion before sleep, delivering essential Omega-3 fatty acids for joints.",
  },
];
